ALTER TABLE nguoi_dung
  MODIFY id INT NOT NULL AUTO_INCREMENT FIRST,
  MODIFY tai_khoan VARCHAR(255) NOT NULL AFTER id;

ALTER TABLE dat_ve
  MODIFY id INT NOT NULL AUTO_INCREMENT FIRST,
  MODIFY tai_khoan VARCHAR(255) NOT NULL AFTER id,
  MODIFY ma_lich_chieu INT NOT NULL AFTER tai_khoan,
  MODIFY ma_ghe INT NOT NULL AFTER ma_lich_chieu;
